### ISSUE TITLE
TypeErrors on list_relations_editor_box.js 

### ISSUE THREAD

**Issue by qoheleth-tech** [xtuple/xtuple#1038]
Steps to reproduce:
1. Open Customer 
2. Navigate to tax registration relation to add new tax registration.
3. instead of adding any, click delete and click "Back" to Customer list.
4. re-enter same Customer workspace. 
5. Navigate to tax registrations relation and click "New" button. 
6. In console note error "TypeError e.hasNode(...) is null"
I've confirmed this error in two implementation of the list_relations_editor_box.js.

Next error:
Do the same as above, except "Save" main workspace before clicking "Back".
Once re-entered, note console error "this.$.list is undefined.
I've have only confirmed this error in one implementation in one extension, but I believe it to be likely present elsewhere as well.

**Comment by gilmoskowitz** [comment]
This bug appears to be fixed in 4.9.x.
