### ISSUE TITLE
Useful text if a list is empty due to no privileges

### ISSUE THREAD

**Issue by shackbarth** [xtuple/xtuple#1512]
If the user does not have the privileges to see the models of a list, then the list will show up blank. It looks just like if the list were empty. Within the list code,
https://github.com/xtuple/xtuple/blob/v4.4.1/lib/enyo-x/source/views/list.js
`this.value` is the backing collection, so `this.value.model.prototype.canView()` is the appropriate privilege check. 

If it's the priv is false, it would be appropriate to bubble up an `onMessage` event to the navigator. 

https://github.com/xtuple/xtuple/blob/v4.4.1/lib/enyo-x/source/views/navigator.js#L60

Adding an `onMessage` bubblable event into XV.List would be reasonable.

Note that for many lists, *anyone* can see the (summarized) list model. This would only be applicable for lists, like for `SalesOrder`, with view restrictions even on the lightweight list models.
https://github.com/xtuple/xtuple/blob/v4.4.1/enyo-client/database/orm/models/sales_order.json#L1760

**Comment by jcarlin** [comment]
Also text for empty lists.

**Comment by jcarlin** [comment]
@gpazo this may be a good one for you

**Comment by jcarlin** [comment]
Resolved https://github.com/xtuple/xtuple/pull/2466
