### ISSUE TITLE
4.4.1 to 4.5.0 tehead should be te.tehead...

### ISSUE THREAD

**Issue by xtpclark** [xtuple/xtuple#1583]
insert into tehead  - appears in the build_app.js generated SQL. Got error, changed the temp_qry.sql 
applied sql manually then got...

CREATE RULE
ERROR:  relation "tehead" does not exist
LINE 2: update tehead set

Should be te.tehead... or was this supposed to figure out the search path automatically?

**Comment by gilmoskowitz** [comment]
no longer in scope, possibly resolved by other changes
