### ISSUE TITLE
Update pluralize function 

### ISSUE THREAD

**Issue by lynnaloo** [xtuple/xtuple#1586]
The current pluralize function in the tools library is insufficient and needs to be updated to prevent bugs: https://github.com/xtuple/xtuple/blob/master/enyo-client/application/source/widgets/parameter.js#L78.

Current pluralize function could be replaced with npm module: https://www.npmjs.org/package/pluralize.

**Comment by bendiy** [comment]
https://github.com/epeli/underscore.string#underscorejslo-dash-integration
https://github.com/geetarista/underscore.inflections
https://github.com/pksunkara/inflect
https://github.com/blakeembrey/pluralize

Using an Underscore/Lowdash mixin would be straight forward.
