### ISSUE TITLE
Create Operation Type in Manufacturing

### ISSUE THREAD

**Issue by shackbarth** [xtuple/xtuple#1832]
Add new concept - Operation Type - to manufacturing client (qt and mobile). This is used to classify a Std Operation or W/O Operation into different types.

Required for Quality Development so we can determine what operation is a Inspection/Test operation, and when creating Rework operations

https://github.com/xtuple/private-extensions/blob/master/source/manufacturing/foundation-database/xtmfg/tables/pkgscript/standardOperation.js

https://github.com/xtuple/private-extensions/blob/master/source/manufacturing/foundation-database/xtmfg/tables/pkgscript/woOperation.js

plus new private-extension screens/widgets etc.

**Comment by jcarlin** [comment]
Resolved.
