### ISSUE TITLE
Navigating between child workspaces causes error in parent workspace save

### ISSUE THREAD

**Issue by andersdd** [xtuple/xtuple#1860]
Steps to reproduce:
Go into a Work Order workspace where two or more Routing children have been created.
As this is presented as a gridbox, go into the child workspace itself.
Press the "Previous" (or "Next") button to move between children.
Make a change on one of the children.
Press Back to go to the parent workspace.
Press save.

Error occurs in enyo.kind.valueChanged (grid_box.js:623)

I have found this occurs even if the edit was done on the parent workspace

**Comment by gilmoskowitz** [comment]
fixed by https://github.com/xtuple/xtuple/pull/2506
