### ISSUE TITLE
Run the rest of mobile inventory through paces

### ISSUE THREAD

**Issue by shackbarth** [xtuple/xtuple#1864]
IssueToShipping is now a known quantity, but there's also:

    Shipping: ‘Issue to Shipping’, ‘Return from Shipping’, ‘Ship Order’
    Receiving: ‘Enter Receipt’, ‘Post Receipt’
    Manufacturing: ‘Issue Materials/Return Materials’, Post Production’
    Inventory: ‘Inventory Adjustment’

**Comment by gpazo** [comment]
@jcarlin ok to close this?
