### ISSUE TITLE
Date and Currency doesn't honor the locale

### ISSUE THREAD

**Issue by ssshyam** [xtuple/xtuple#1871]
German Locale:

Date format: dd.mm.yyyy
Number separator = '.'
Decimal separator = ','

Steps to reproduce:-
1. Login to xTuple  Mobile Web application and navigate to Setup->User Accounts, open the logged in user account, change the Locale to 'German' and logout from the application
2. Re-login to the application with the same user, navigate to Sales->Sales Orders and create a sales order
3. Observe that Date format and Currency format is not honored the locale set for the user

**Comment by gilmoskowitz** [comment]
replaced by https://www.xtuple.org/xtincident/view/bugs/26788
