### ISSUE TITLE
Fix JSON-Schema for service dispatch functions

### ISSUE THREAD

**Issue by bendiy** [xtuple/xtuple#1921]
The JSON-Schema for several dispatch functions is incorrect:
https://github.com/xtuple/private-extensions/blob/4_7_x/source/inventory/database/source/xm/javascript/inventory.sql#L782-L791

Follow the `XM.Customer.itemPrice()`pattern here that uses an `attributes` array property:
https://github.com/xtuple/xtuple/blob/4_7_x/enyo-client/database/source/xm/javascript/customer.sql#L95-L134

Ran into this issues here: https://github.com/xtuple/xtuple/issues/1888

**Comment by gilmoskowitz** [comment]
Replaced by https://www.xtuple.org/xtincident/view/bugs/26786
