### ISSUE TITLE
item number stays on the screen SOE( version 4.7)

### ISSUE THREAD

**Issue by tomdatkins** [xtuple/xtuple#2005]
I have saw this before but could not reproduce I think I now can.

STR:
go to a sales order, hit new, add ttoys as the customer, click new item. In the item box just type d, ou should see dtruck. Now hit enter, you should get 2 blank items with Dtruck being the 3rd and Dtruck stuck on the scree where even if you go back and cancel the Dtruck remains right there.

**Comment by gilmoskowitz** [comment]
https://github.com/xtuple/xtuple/pull/2511
