### ISSUE TITLE
REST Issue To Shipping (Serialized) never responds

### ISSUE THREAD

**Issue by discountscott** [xtuple/xtuple#2025]
We can issue items to shipping no problem - but whenever we try to issue an item from SO to shipping that is serialized inventory the REST API never responds. We get a 504 time out response.

I have tried submitting both the UUID of the trace as well as the serial number itself (documentation says to just use the number).

"trace": {
          "title": "Trace",
          "description": "Trace (Lot or Serial) Number",
          "type": "string"
        }

Submitting the following. {"attributes":["9066e109-6765-4919-ae81-6708440ca674",1,{"detail":{"quantity":1,"location":"354ed871-ef47-467d-e0d8-8cc1943fc616","trace":"123533"}}]}

![image](https://cloud.githubusercontent.com/assets/5454596/5159021/d2a4f83c-7322-11e4-8b0a-d133ba70dd7c.png)

**Comment by discountscott** [comment]
any updates on this??

**Comment by bendiy** [comment]
@discountscott I've tracked down a bug that was causing you issues here. There are two PR you should merge to fix this:
https://github.com/xtuple/private-extensions/pull/573
https://github.com/xtuple/xtuple/pull/2236

These lines are the relevant ones:
https://github.com/bendiy/private-extensions/blob/issue-to-shipping/source/inventory/database/source/xm/javascript/inventory.sql#L1051
https://github.com/bendiy/private-extensions/blob/issue-to-shipping/source/inventory/database/source/xm/javascript/inventory.sql#L1059
https://github.com/bendiy/xtuple/blob/issue-to-shipping/foundation-database/public/functions/distributeitemlocseries.sql#L10

There were two problems I found.
1. The `XM.Inventory.issueToShipping` function did not return anything, causing the nginx timeout. It was actually doing the issue to shipping, just not telling you.
2. The `distributeItemlocSeries` function had a debug flag set, sending `NOTICE` messages to the REST API layer that is typically used to pass status messages to the REST API layer so we know when things succeed or throw errors. We couldn't parse the `distributeItemlocSeries` notices, so we could never send back `client.status=  [ '{"code":200,"message":"OK"}' ]`

Please give these fixes a try and let us know if it worked.
