### ISSUE TITLE
Expose Pricing Schedules in REST

### ISSUE THREAD

**Issue by discountscott** [xtuple/xtuple#2038]
Would anyone else benefit from pricing schedules being exposed in the REST API?

Might tackle this...

Would be nice to be able update our QTY discounts (pricing schedules) via the REST api. Would make our Magento integration (in progress) truly not require any human interaction when syncing our pricing rules from Magento <-> xTuple.

**Comment by gilmoskowitz** [comment]
Replaced by https://www.xtuple.org/xtincident/view/bugs/26784
