### ISSUE TITLE
zapier integration

### ISSUE THREAD

**Issue by shackbarth** [xtuple/xtuple#2040]
This is still a bit speculative and the requirements still need to be defined, but it would be great to get some actions and triggers working between xTuple and Zapier. 

We could start by scratching our own itches, and add `Incidents` for integration with github and/or redmine. Or we could start with `SalesOrder` for possible eCommerce uses. The former would be an easier way for us to get our feet wet.

**Comment by MarketingxTuple** [comment]
per Gil's comment "...something seemingly simple like mail campaigns can get ugly quickly, for example if the marketing component includes data cleansing tools." - that would be extremely helpful down the road, but initially, we need a simple way to send targeted emails via MailChimp or ConstantContact from xTuple CRM https://zapier.com/zapbook/use-cases/email-list-building/ 

Additionally, we need to send form submissions into our CRM to build those targeted lists https://zapier.com/zapbook/customers/salespeople/ 

I believe Pierce had advocated for RSS feeds, related to Knowledge Base https://zapier.com/app/explore?services=rss
