### ISSUE TITLE
Setup > Items list does not load

### ISSUE THREAD

**Issue by bendiy** [xtuple/xtuple#2109]
In the mobile client, I cannot access the list of items.
```
Uncaught ReferenceError: Globalize is not defined
```

**Comment by shackbarth** [comment]
Do you have globalize in your `bower_components` directory? Try a `bower install`, or possibly an `npm install -g bower`. All this should be taken care of for new environments via recent changes to `install_xtuple.sh`.

**Comment by bendiy** [comment]
Running `bower install` seems to have fixed it. Thanks
