### ISSUE TITLE
Add 2015 periods to  postbooks_demo_data.sql 

### ISSUE THREAD

**Issue by jgunderson** [xtuple/xtuple#2111]
Add 2015 periods to  postbooks_demo_data.sql

**Comment by andersdd** [comment]
I have written a feature in the qt client to copy the last fiscal year into a new fiscal year.  If you want to create an entirely new fiscal year and periods that mimic the current fiscal year you can use this function.

https://github.com/andersdd/xtuple/blob/copyFiscalPeriods/foundation-database/public/functions/copyaccountingyearperiod.sql

**Comment by gilmoskowitz** [comment]
See 1f736c77
