### ISSUE TITLE
 Unable to build the database in 4_9_x branch

### ISSUE THREAD

**Issue by ssshyam** [xtuple/xtuple#2112]
1. Fetch and merge the latest code of xtuple, xtuple-extensions, private-extensions against 4_9_x branch
2. From xTuple repository, run 'sudo ./scripts/build_app.js -d databasename' from xtuple repository and it displays following error

Error :
~/src/xtuple$ sudo ./scripts/build_app.js -d databasename
building client core
building crm
building sales
building billing
building purchasing
building project
building oauth2
building inventory
building manufacturing
building distribution
error: undefined undefined '/home/zenqa/src/xtuple/database/source/xt/trigger_functions/createwf_after_insert.sql does not exist'
/home/zenqa/src/xtuple/database/source/xt/trigger_functions/createwf_after_insert.sql does not exist

Additional Information : Issue resolved after adding 'createwf_after_insert.sql' file

**Comment by shackbarth** [comment]
This will be fixed when @gpazo does a merge-forward of 4_8_x into 4_9_x

**Comment by gpazo** [comment]
old issue, closing.
