### ISSUE TITLE
Unable to create a database on the pull request issued by Anderson and Greg against 4_9_x branch

### ISSUE THREAD

**Issue by harikajulaganti** [xtuple/xtuple#2113]
1. Navigate to xTuple repository, fetch the code from the remote Anderson/Greg using the command 'git fetch remotename'
2. Checkout to the pull issued branch using 'git checkout remotename/PRbranchName'
3. Create a new branch in our local repository 'git checkout -b branch_name'
4. Merge the code from 4_9_x 'git merge xtuple/4_9_x'
5. Create database in Postgre SQL with 480 masterref backup file
6. Run 'sudo ./scripts/build_app.js -d databasename' from xtuple repository and observe that following error is displayed

Error :
~/src/xtuple$ sudo ./scripts/build_app.js -d 17494
building client core
building crm
building project
building sales
building billing
building purchasing
building oauth2
building inventory
building distribution
building manufacturing
info: Applying build to database 17494
error: Cannot install file  /home/zenqa/src/xtuple/scripts/output/build_17494.sql
error: Command failed: psql:/home/zenqa/src/xtuple/scripts/output/build_17494.sql
:43: NOTICE:  function xt.add_column(text,text,text,text,text) does not exist, skipping
psql
:/home/zenqa/src/xtuple/scripts/output/build_17494.sql
:866: NOTICE:  Type seqiss already exists
psql:/home/zenqa/src/xtuple/scripts/output/build_17494.sql:40036:
 ERROR:  cannot change name of input parameter "papopenid"
HINT:  Use DROP FUNCTION postapcreditmemoapplication(integer) first.
 Error: Command failed: psql:/home/zenqa/src/xtuple/scripts/output/build_17494.sql:43: 
NOTICE:  function xt.add_column(text,text,text,text,text) does not exist, skipping
psql:/home/zenqa/src/xtuple/scripts/output/build_17494.sql:866:
 NOTICE:  Type seqiss already exists
psql:/home/zenqa/src/xtuple/scripts/output/build_17494.sql:40036: 
ERROR:  cannot change name of input parameter "papopenid"
HINT:  Use DROP FUNCTION postapcreditmemoapplication(integer) first.
at ChildProcess.exithandler (child_process.js:648:15)
at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
 at Process.ChildProcess._handle.onexit (child_process.js:823:5) killed=false, code=3, signal=null
{ [Error: Command failed: psql:/home/zenqa/src/xtuple/scripts/output/build_17494.sql:43: 
NOTICE:  function xt.add_column(text,text,text,text,text) does not exist, skipping
psql:
/home/zenqa/src/xtuple/scripts/output/build_17494.sql:866: 
NOTICE:  Type seqiss already exists
psql:/home/zenqa/src/xtuple/scripts/output/build_17494.sql:40036:
 ERROR:  cannot change name of input parameter "papopenid"
HINT:  Use DROP FUNCTION postapcreditmemoapplication(integer) first.
] killed: false, code: 3, signal: null }

**Comment by bendiy** [comment]
This should be fixed or a non-issue now.
https://github.com/xtuple/xtuple/blob/4_10_x/foundation-database/public/functions/postapcreditmemoapplication.sql
