### ISSUE TITLE
ccpayments lists payments twice if customer is in two customer groups.

### ISSUE THREAD

**Issue by jwirt** [xtuple/xtuple#2116]
The ccpayments.mql file needs an additional <? if exists ?>  tag on line# 45 of cpayments.mql.

Something like:
<? if exists("custgrp_id") ?>
 LEFT OUTER JOIN custgrpitem ON (custgrpitem_cust_id=cust_id)
<? endif ?>)

At the current time if no custgrp_id parameter is passed but the customer is in more than one customer group then a row is returned for each customer group for which the customer is a member.

Sorry if this isn't the correct place to report the issue or to post the proposed fix.  Just wanted to get it somewhere you guys would be aware of it.

**Comment by bendiy** [comment]
https://github.com/xtuple/xtuple/blob/4_10_x/foundation-database/public/tables/metasql/ccpayments.mql#L45

**Comment by gilmoskowitz** [comment]
Replaced by https://www.xtuple.org/xtincident/view/bugs/26783
