### ISSUE TITLE
Data source error is generated on selecting to create a sales order for an item linked to work order

### ISSUE THREAD

**Issue by harikajulaganti** [xtuple/xtuple#2122]
Pre-condition : Ensure that selected item site should have 'Work Orders' checkbox checked under 'Auto Create For Sales Order' section 
Steps to reproduce :

1. Sales->Sales Orders->New
2. Select a customer (say 'TTOYS'), select 'New' in the Line Items tab, select an item (Say 'YTRUCK1'), enter quantity and click on 'Save' button to save the Sales order
3. Observe that 'Error: Error: more than one row returned by a subquery used as an expression' is displayed in console and server is crashed

**Comment by jcarlin** [comment]
Resolved.
