### ISSUE TITLE
Vendor Workbench not showing addresses 

### ISSUE THREAD

**Issue by comtineo01** [xtuple/xtuple#2131]
Successfully imported (via CSVimp) Vendor and Contact api's but not seeing the addresses show up on the list for vendors when I open up the Vendor Workbench in xTuple.

Is there yet another place I need to store that data?

**Comment by szuke** [comment]
Did you import to the api.vendoraddress?

**Comment by comtineo01** [comment]
This is where I show my complete lack of IT skills (accountant). I tried the api.vendoraddress import but it demands a 'Vendor Address Number'....when I looked up the appropriate info via the pgAdmin and added the correct number to each vendor, it threw a 'cannot use as it is in use' error.

Do I reassign the Vendors a new set of numbers that overwrites their current numbers?  Will that effect the data elsewhere?

**Comment by comtineo01** [comment]
Hmmm, still no joy. The Vendor_address_number for each vendor is identical to the Vendor_number  according to the view in PGadmin, but it's giving me the 'in use' error.

**Comment by bixwilson** [comment]
Vendor address number is actually just used as a way to identify different addresses for a vendor. One way to use it is to just number the addresses sequentially for each vendor. So, if a vendor has 3 different addresses, the vendor_address_numbers would be 1, 2, and 3. The numbers must be unique for each vendor. So each vendor can have a 1, 2, and 3, but a single vendor cannot have 2 address numbers that are the same, eg. 1 and 1. I hope that clarifies things a bit!

**Comment by comtineo01** [comment]
Okay that makes sense. Mapped and Imported api.vendoraddress with no errors. Included address info.
But addresses still not showing up on the list from the Vendor Icon.

**Comment by comtineo01** [comment]
To Recap.....Vendor Addresses show up in the field columns when viewed thru the PGAdmin, but do not appear on the Vendor list when pulled up via the Vendor WorkBench (add1, add2, City, St, Zip, Country - all blank). They do populate the correct fields when creating a new PO. 

Side note - I see the boolean entry for if 1099, but can't seem to find the field to import the actual EIN#.

**Comment by bixwilson** [comment]
Can you post a screenshot of the screen where you expect the addresses to show, but they are not?

**Comment by comtineo01** [comment]
Certainly, should of thought of that myself.


![image](https://cloud.githubusercontent.com/assets/9354298/5847098/28433cb4-a18f-11e4-98c5-911041b7d88b.png)

**Comment by bixwilson** [comment]
Now you've entered the vendor addresses, but there's one more step to get that address to show up as the main address for the vendor. You need to do an update to the api.vendor table to add the correct address_number to the table.

If you query api.address you'll see that each address you entered has an address_number. That is the number that needs to be referenced by api.vendor.

**Comment by comtineo01** [comment]
I truly appreciate your help with this.

It seems to already match up fine. As the screenshot below shows;
GME Supply Company has a address_number of 41 on both views 
GPD Group has an address_number of 42 on both views

![image](https://cloud.githubusercontent.com/assets/9354298/5858550/a4de69e4-a219-11e4-9c09-92b1d5d74986.png)

**Comment by szuke** [comment]
Can you look up the same thing on the public.vendinfo and public.addr tables? These are joined on the _id fields and we need to be sure that these are tying out.

Scott
