### ISSUE TITLE
Multiple Companies in same database

### ISSUE THREAD

**Issue by comtineo01** [xtuple/xtuple#2139]
We have 5 companies that are separate entities (not owned by each other in any way) but do business with each other on a regular basis.

In order to keep reporting, vendors, customers etc. simpler and less jumbled together, would it make more sense to create individual databases for each one rather than use the Company prefix on the GL Account #'s?

**Comment by szuke** [comment]
I would keep them as separate database instances. Do you need rolled up financials for these? It doesn’t sound like it?

Scott

**Comment by comtineo01** [comment]
No, don't need the rolled up financials. I guess was enticed by the company prefix on the account #'s into thinking it would work all in one database to save server space. But four of the companies are fairly small at the moment, so probably not an issue.

Thanks for the input Mr. Zuke!
