### ISSUE TITLE
Vendor EIN#

### ISSUE THREAD

**Issue by comtineo01** [xtuple/xtuple#2140]
I see the boolean Y/N for if a Vendor is 1099 eligible, but can't find the location to import the actual EIN number. Is it named something I wouldn't recognize?

**Comment by bixwilson** [comment]
Tax IDs are stored in a different table called taxreg. There is no view in the API schema for this table so you'll have to insert directly to the taxreg table in the public schema. The key field is taxreg_rel_id, which is where you insert the vend_id from the vendinfo table (not the vendor_number).

**Comment by szuke** [comment]
I’ve seen the vendor account number used for this, although I prefer to use a tax registration number. The tax registration number is on the same screen as the 1099 check box, but it’s not accessible in the api view.

The api view for this is quite simple. The api.custtax gives a great model for a potential api.vendtax view.

I’d love to knock this out, but I wouldn't be able to touch this until late next week at the earliest.

Scott

**Comment by bixwilson** [comment]
It would be nice to have a view for vendtax. If you get the time to do 
it, please go ahead!


On 1/22/15 11:02 AM, szuke wrote:
> I’ve seen the vendor account number used for this, although I prefer 
> to use a tax registration number. The tax registration number is on 
> the same screen as the 1099 check box, but it’s not accessible in the 
> api view.
>
> The api view for this is quite simple. The api.custtax gives a great 
> model for a potential api.vendtax view.
>
> I’d love to knock this out, but I wouldn't be able to touch this until 
> late next week at the earliest.
>
> Scott
>
>
>
> From: comtineo01 
> <notifications@github.com<mailto:notifications@github.com>>
> Reply-To: xtuple/xtuple 
> <reply@reply.github.com<mailto:reply@reply.github.com>>
> Date: Thursday, January 22, 2015 at 10:42 AM
> To: xtuple/xtuple 
> <xtuple@noreply.github.com<mailto:xtuple@noreply.github.com>>
> Subject: [xtuple] Vendor EIN# (#2140)
>
>
> I see the boolean Y/N for if a Vendor is 1099 eligible, but can't find 
> the location to import the actual EIN number. Is it named something I 
> wouldn't recognize?
>
> —
> Reply to this email directly or view it on 
> GitHub<https://github.com/xtuple/xtuple/issues/2140>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/xtuple/xtuple/issues/2140#issuecomment-71043885>.
>


-- 

BC Wilson
Director of Cloud Services @xTuple
+1-757-461-3022 x110
bc@xTuple.com <mailto:bc@xtuple.com>

xTuple.com <http://www.xtuple.com/> – Download FREE PostBooks ERP, CRM, 
accounting software
xTuple.org <http://www.xtuple.org/> – Contribute to World’s #1 open 
source ERP community
NextBusinessBlog.com <http://www.nextbusinessblog.com/> – Join the 
global innovation conversation

**Comment by szuke** [comment]
Here it is…




-- View: api.vendtax

-- DROP VIEW api.vendtax;

CREATE OR REPLACE VIEW api.vendtax AS
 SELECT vendinfo.vend_number::character varying AS vendor_number, taxauth.taxauth_code::character varying AS tax_authority, taxreg.taxreg_number AS registration_number
   FROM vendinfo, taxauth, taxreg
  WHERE taxreg.taxreg_rel_type = 'V'::bpchar AND taxreg.taxreg_rel_id = vendinfo.vend_id AND taxreg.taxreg_taxauth_id = taxauth.taxauth_id;

ALTER TABLE api.vendtax
  OWNER TO admin;
GRANT ALL ON TABLE api.vendtax TO admin;
GRANT ALL ON TABLE api.vendtax TO xtrole;
COMMENT ON VIEW api.vendtax
  IS 'Vendor Tax Registration';

-- Rule: "_DELETE" ON api.vendtax

-- DROP RULE "_DELETE" ON api.vendtax;

CREATE OR REPLACE RULE "_DELETE" AS
    ON DELETE TO api.vendtax DO INSTEAD  DELETE FROM taxreg
  WHERE taxreg.taxreg_rel_type = 'V'::bpchar AND taxreg.taxreg_rel_id = getvendid(old.vendor_number::text) AND taxreg.taxreg_taxauth_id = gettaxauthid(old.tax_authority::text);

-- Rule: "_INSERT" ON api.vendtax

-- DROP RULE "_INSERT" ON api.vendtax;

CREATE OR REPLACE RULE "_INSERT" AS
    ON INSERT TO api.vendtax DO INSTEAD  INSERT INTO taxreg (taxreg_rel_type, taxreg_rel_id, taxreg_taxauth_id, taxreg_number)
  VALUES ('V'::bpchar, getvendid(new.vendor_number::text), gettaxauthid(new.tax_authority::text), new.registration_number);

-- Rule: "_UPDATE" ON api.vendtax

-- DROP RULE "_UPDATE" ON api.vendtax;

CREATE OR REPLACE RULE "_UPDATE" AS
    ON UPDATE TO api.vendtax DO INSTEAD  UPDATE taxreg SET taxreg_number = new.registration_number
  WHERE taxreg.taxreg_rel_type = 'V'::bpchar AND taxreg.taxreg_rel_id = getcustid(old.vendor_number::text) AND taxreg.taxreg_taxauth_id = gettaxauthid(old.tax_authority::text);

**Comment by szuke** [comment]
I'll work on doing this the "right" way.

**Comment by bixwilson** [comment]
You mean, committing it to the repo? That's ok. I've passed it on to the developers.

**Comment by szuke** [comment]
Thanks...

**Comment by comtineo01** [comment]
Okay - Thanks Gentlemen! Nice to know I wasn't just being dense on at least one issue.
