### ISSUE TITLE
pgcrypto

### ISSUE THREAD

**Issue by comtineo01** [xtuple/xtuple#2144]
Is  xTuple 4.7.0 compatible with the latest release of pgcrypto or should we use an older one?

Is this still the proper way to set up a key? 
http://www.xtuple.org/faq/xtuple-faq/point-sale-pos/how-do-i-set-local-credit-card-encryption-key-file

I'm getting an error     'Cannot read encrypted information from database'

**Comment by xtpclark** [comment]
Use the pgcrypto that you have.

Create a PLAIN TEXT/ASCII text file.  It can contain any content as long as it is plain text. Use Notepad, or vi - not Word or Wordpad.

Create a file:
<pre>
nano MyKey.txt
</pre>
Enter some text.
<pre>
This is some key.
</pre?>
Save the file and check it.

<pre>
bash-4.1$ file MyKey.txt 
MyKey.txt: ASCII text
</pre>

This file needs to be in a directory local to the CLIENT computer as the setup for the key is a GLOBAL setting. It needs to be a common path for All of the similar OS's
i.e.
c:\ for windows
/Users/ for OSX
/somewhere for linux
OR it can be kept in the top level directory of the xTuple client folder. (and do not specify a path in the setup screen) <- I'm 98% sure this information is still correct.

**Comment by comtineo01** [comment]
Thank you so much!
