### ISSUE TITLE
enyo-client/database should be empty in 4_9_x and later

### ISSUE THREAD

**Issue by gilmoskowitz** [xtuple/xtuple#2154]
we need to merge https://github.com/xtuple/xtuple/blob/4_9_x/enyo-client/database/source/xt/trigger_functions/createwf_after_insert.sql into https://github.com/xtuple/xtuple/blob/4_9_x/database/source/xt/trigger_functions/createwf_after_insert.sql and clear enyo-client/database again

**Comment by gpazo** [comment]
@gilmoskowitz this directory doesn't exist anymore, okay to close?

**Comment by gilmoskowitz** [comment]
Yes - There's only one createwf_after_insert.sql now.
