### ISSUE TITLE
Date picker cannot pick Jan 29th

### ISSUE THREAD

**Issue by bendiy** [xtuple/xtuple#2159]
Keeps giving me 1/1/2015
![date-picker](https://cloud.githubusercontent.com/assets/571574/6217799/06dcc234-b5d5-11e4-83d6-83984bfc6e76.png)

**Comment by bendiy** [comment]
also cannot select the 30th or 31st. I think this is messed up by February having 28 days. All days in January work except those after the 28th. Then it ends up selecting the corresponding date in the first week of January.
29th -> 1st
30th -> 2nd
31st -> 3rd

**Comment by gpazo** [comment]
#2365 resolves this

**Comment by amikheychik** [comment]
Just in case, this is happening no only on 31st. It basically happens on any day, seems to be related to summer/winter time
