### ISSUE TITLE
Bergin Sales Order list: Uncaught ReferenceError: Globalize is not defined

### ISSUE THREAD

**Issue by bendiy** [xtuple/xtuple#2162]
Can't get a list to load because of this error.

**Comment by bendiy** [comment]
Tried #2109 did not fix this. Any ideas @shackbarth ?

**Comment by shackbarth** [comment]
I'd pose the same question as I did in #2109: do you have Globalize in your `bower_components` directory?

**Comment by shackbarth** [comment]
If you run it in debug mode and look at the network traffic, does the app try and fail to find the globalize.js file?

**Comment by bendiy** [comment]
The instance was running from the wrong version code base, so my bower fix attempts weren't taking. It's working now after pointing to the right directory.
