### ISSUE TITLE
Editing a GL Account removes the Profit Center prefix

### ISSUE THREAD

**Issue by comtineo01** [xtuple/xtuple#2163]
I've imported the CoA successfully, adding the Profit Center prefix. All of them are a "1" for now, but we are preparing for an expansion.

When I edit an account (to enhance the description for example) and save it, the Profit Center prefix is not available to edit and the prefix disappears from our CoA when it is saved. I've tried both with and without a checkmark in the 'Allow Free-Form Profit Centers' in the Accounting Setup and cannot get it to save an edit without removing the Profit Center prefix or allowime to edit the Account # to add it back in. 

Please tell me that I don't have to delete and reenter a GL account to edit it. This will not work once we have balances in the system I assume.

**Comment by comtineo01** [comment]
Just discovered this also happens with the subaccount suffix. They disappear and are not editable.

**Comment by nedlilly** [comment]
The number segments are not supposed to be editable, but they are also not supposed to "disappear"... can you post a screenshot of an individual Ledger Account Number screen?

**Comment by comtineo01** [comment]
Double Clicked on it to bring it up. As you can see on the CoA listing, it has a Profit Center and Subaccount. But even if I don't edit anything in the pop up window, if I hit 'Save', they will both disappear. 
![image](https://cloud.githubusercontent.com/assets/9354298/6049204/18f5c578-ac7b-11e4-9668-19b091d9c2d5.png)

**Comment by davidbeauchamp** [comment]
On the ledger account setup, do you have "allow free form" for the profit center or sub accounts? If it is not set to allow free form, you need to define the subaccount and profit centers before you can use them, under accounting > ledger accounts.

**Comment by comtineo01** [comment]
Yup. I had those set for the original import. Left them as is, except for a short experiment to see if disabling the 'Free-Form' part might get the numbers to stick. But no joy. Currently both are back on Free-Form with the segment size set to 2.
