### ISSUE TITLE
Accounts not showing up in the Cost Categories Set up

### ISSUE THREAD

**Issue by comtineo01** [xtuple/xtuple#2164]
In the tutorial Video, the acct #'s appear when an account is selected. When I do the same, the white box remains blank. It does show the name to the side as in the video, but no acct# in the white box.

Am I missing a previous set up procedure?

![image](https://cloud.githubusercontent.com/assets/9354298/6046479/21b8b656-ac68-11e4-88bf-a28a0a04854c.png)

**Comment by davidbeauchamp** [comment]
This can happen if you have options enabled in your ledger accounts that you haven't filled in values for. Under accounting > setup, the general ledger options allow you to turn on "Company", "Profit Center" and "SubAccount" segments within your ledger accounts.If you have any of those three enabled, your ledger accounts need to include values for those segments.

**Comment by comtineo01** [comment]
Yeah, we are using Profit Center (or trying to.....https://github.com/xtuple/xtuple/issues/2163), but not the Company segment. It's turned off. 

Unless I've tried to edit the Account, the Profit Center prefixes all show on the CoA. 

Oh Wait a minute...Subaccounts...so even if that particular account isn't in a group that uses subaccounts, all accounts need a default subaccount #? That seems very odd.
