### ISSUE TITLE
WO Post Production Lot Distribute Detail List is Broken

### ISSUE THREAD

**Issue by bendiy** [xtuple/xtuple#2171]
When adding a Detail item to the list, only Quantity is enabled. The rest of the fields are grayed out. Cannot Post Production for any Lot items because of this.

**Comment by jcarlin** [comment]
Fixed by https://github.com/xtuple/private-extensions/pull/557

![screen shot 2015-02-12 at 4 53 53 pm](https://cloud.githubusercontent.com/assets/1823527/6178762/c3118558-b2d7-11e4-880e-86fc28b11437.png)
