### ISSUE TITLE
Selecting a field on mobile device inserts the cursor instead of highlighting value

### ISSUE THREAD

**Issue by bendiy** [xtuple/xtuple#2172]
This kills the UX because the user has to place the cursor, delete the value and THEN enter a quantity.

**Comment by jcarlin** [comment]
I just tested this out against https://github.com/xtuple/xtuple/pull/2167 and it looks to be corrected, thanks to https://github.com/xtuple/xtuple/pull/2167#discussion-diff-24183817R44. You can close this, we'll reopen if we see any specific inputs with this behavior.
