### ISSUE TITLE
Rename Issue Material menus to Maintain Materials

### ISSUE THREAD

**Issue by bendiy** [xtuple/xtuple#2173]

**Comment by bendiy** [comment]
https://github.com/xtuple/private-extensions/pull/555

**Comment by bendiy** [comment]
@jcarlin: This is done for any of the gear icon lists, but I'm not sure if we want to also change this:
![issue](https://cloud.githubusercontent.com/assets/571574/6139095/fe897cf6-b144-11e4-995c-5f58c737e3ef.png)

**Comment by jcarlin** [comment]
The screen shot is not clear. Where was this?

On Tue, Feb 10, 2015 at 5:51 PM, bendiy <notifications@github.com> wrote:

> @jcarlin <https://github.com/jcarlin>: This is done for any of the gear
> icon lists, but I'm not sure if we want to also change this:
> [image: issue]
> <https://cloud.githubusercontent.com/assets/571574/6139095/fe897cf6-b144-11e4-995c-5f58c737e3ef.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xtuple/xtuple/issues/2173#issuecomment-73809715>.
>



-- 
Julian Carlin

(US) 612-234-4124

**Comment by bendiy** [comment]
Manufacturing > Work Order > Issue Material

**Comment by jcarlin** [comment]
Here's mine from Manufacturing > Work Orders (list), select a WO, tap gear:

![screen shot 2015-02-11 at 10 36 50 am](https://cloud.githubusercontent.com/assets/1823527/6151219/fe9b7d4e-b1d9-11e4-85a5-704a91ae5419.png)

**Comment by jcarlin** [comment]
Ahhh, but I did miss this one (inside of work order workspace):
![screen shot 2015-02-11 at 10 38 29 am](https://cloud.githubusercontent.com/assets/1823527/6151242/2d1461cc-b1da-11e4-9d31-3273213f0fca.png)

**Comment by jcarlin** [comment]
Ok, finally understood that you were talking about the header title of the Issue Material/Return Material list container where it still says Issue Material, updating now in my pr.

**Comment by jcarlin** [comment]
Resolved by https://github.com/xtuple/private-extensions/pull/555 and the finally https://github.com/xtuple/private-extensions/pull/562
