### ISSUE TITLE
Switch Mobile Report printing to use the OpenRPT route

### ISSUE THREAD

**Issue by bendiy** [xtuple/xtuple#2187]
Most common actions like `Issue to Shipping -> Ship Order -> Print Invoice` should use the OpenRPT route so the Mobile Client and Qt Client print the same report.

**Comment by bendiy** [comment]
Support #2217 too.

**Comment by jcarlin** [comment]
Some QA code that does this: https://github.com/xtuple/private-extensions/blob/4_9_x/source/quality/client/views/list.js#L379-L401

**Comment by gilmoskowitz** [comment]
I'm going to change this from "most" to "all" common actions - the Mobile Web client should use the same reports as the Qt desktop client whenever possible.
