### ISSUE TITLE
Issue Material list needs header and correction of item text overflow

### ISSUE THREAD

**Issue by jcarlin** [xtuple/xtuple#2189]
![issue-material_720](https://cloud.githubusercontent.com/assets/1823527/6175727/d98b0c0a-b2be-11e4-88ef-edea61c0680b.png)

**Comment by bendiy** [comment]
There are several lists that are like this, not just Issue Material. Please check all Workflow activity item lists so they are fixed for mobile inventory.

**Comment by bendiy** [comment]
The missing headers are a major UX issue as the user has no idea what any of the qty values are for. At Shipping? Qty Remaining? Very confusing without the headers.

The text overflow makes some of this impossible to read as well.

**Comment by jcarlin** [comment]
Should we make in similar to Issue to Shipping layout with each row having 3 rows of content?

![screen shot 2015-02-20 at 1 59 28 pm](https://cloud.githubusercontent.com/assets/1823527/6308293/e4015a5e-b908-11e4-905e-6d9e5b10a8ca.png)
![screen shot 2015-02-20 at 1 58 48 pm](https://cloud.githubusercontent.com/assets/1823527/6308294/e401ef3c-b908-11e4-9b86-84c0da3c29b5.png)

**Comment by gilmoskowitz** [comment]
@jcarlin - if we expect the "issue/return material" ui to be used on phone-sized devices, i'd go with three rows of data so it fits. if this is more of a desktop or tablet feature then the wide rows should be ok.
