### ISSUE TITLE
Relocate Inventory `SOURCE` and `TARGET` panels require browser reload to populate

### ISSUE THREAD

**Issue by jcarlin** [xtuple/xtuple#2191]
These load exactly once in the app. If you ever come back to it, you have to refresh the browser to get them to load again. Then they will only load that one time before needed to be refreshed again.
![relocate](https://cloud.githubusercontent.com/assets/1823527/6177202/2a61ff5c-b2ca-11e4-9b62-7e1dc9842087.png)

**Comment by gilmoskowitz** [comment]
resolved by https://github.com/xtuple/private-extensions/pull/607
