### ISSUE TITLE
provide barcode scanning functionality for Relocate Inventory

### ISSUE THREAD

**Issue by jcarlin** [xtuple/xtuple#2192]
Note that this requires scans for both Source and Target.

#Use Case:
1. Pallet is in Production area. Need to move to warehouse.
2. Select "Relocate"
3. Enter qty
4. Scan Production location Bin # barcode for Source
5. Put on forklift
6. Drive to warehouse location
7. Scan warehouse location Bin # barcode for Target
8. Post

Note that there could be a significant time delay and screen lock between #4 and #7.

![source-target-scan](https://cloud.githubusercontent.com/assets/571574/6218077/cb2e0b8c-b5d7-11e4-91eb-de482dadca5f.png)

**Comment by bendiy** [comment]
This is a UX issue because we are trying to minimize user input errors by using barcodes. The user can easily select the wrong location from the list and mess up inventory.

**Comment by gilmoskowitz** [comment]
fixed by https://github.com/xtuple/private-extensions/pull/604
