### ISSUE TITLE
simplify printer configuration

### ISSUE THREAD

**Issue by gilmoskowitz** [xtuple/xtuple#2195]
Is there any way we can automate more of https://github.com/xtuple/xtuple/wiki/Mobile-Inventory-Product-Sheet#printing-with-cups ?

**Comment by gilmoskowitz** [comment]
@jcarlin - have recent changes to printing addressed this issue?

**Comment by jcarlin** [comment]
@gilmoskowitz The changes have all been in the UI and have reduced the setup from many objects to just Forms and Labels but nothing has changed in the CUPS side of the required configuration.
