### ISSUE TITLE
Sales Order, type full item number, hit enter, line item triples

### ISSUE THREAD

**Issue by jcarlin** [xtuple/xtuple#2198]
![so-line-tripple](https://cloud.githubusercontent.com/assets/1823527/6190001/838659d0-b364-11e4-9583-d3b0786cdcf8.png)

**Comment by jcarlin** [comment]
Pretty low priority here being that they're not planning to use the client for order entry. I'm going to remove the Mobile Inventory milestone.

**Comment by gpazo** [comment]
resolved by #2403
