### ISSUE TITLE
Issue Material distributing line item detail fails with certain items/quantities

### ISSUE THREAD

**Issue by jcarlin** [xtuple/xtuple#2199]
![wo-issue-mat_1024](https://cloud.githubusercontent.com/assets/1823527/6190965/7f65d2ca-b36b-11e4-80e2-cc1b6734abb9.png)

**Comment by jcarlin** [comment]
I need ssh access to Bergin's pilot server/db for this one. Is there one we can use for dev? https://wsgbergin.xtuplecloud.com/wsgbergin_pilot?

**Comment by jcarlin** [comment]
The only way I was able to reproduce this was with an item that was not set to fractional (setting is within the Item Master) and then issuing a fractional/decimal quantity.

**Comment by gilmoskowitz** [comment]
fixed by https://github.com/xtuple/private-extensions/pull/699
