### ISSUE TITLE
Rename 'Trace' to 'Lot'

### ISSUE THREAD

**Issue by jcarlin** [xtuple/xtuple#2201]
![trace-lot](https://cloud.githubusercontent.com/assets/571574/6218185/dfe08608-b5d8-11e4-89df-65084e2234b6.png)

![trace-popup](https://cloud.githubusercontent.com/assets/571574/6218187/e1f7fc8c-b5d8-11e4-9039-6b2278cc0e58.png)

**Comment by gilmoskowitz** [comment]
resolved by https://github.com/xtuple/private-extensions/pull/563
