### ISSUE TITLE
Add QOH to Issue to Shipping (line item list + workspace)

### ISSUE THREAD

**Issue by jcarlin** [xtuple/xtuple#2204]
We could also add a new concept into order lists that would be an additional column indicating if _**all**_ the stock in available/on hand.

1. Show QOH for the FIFO location
2. Show total QOH for the warehouse and/or all warehouses

This will tell the user that the location has enough to fulfill the line and if not, that there should be enough qty somewhere else to fill it or not.

**Comment by bendiy** [comment]
#2213

**Comment by bendiy** [comment]
This is a UX issue because the user needs this data in the item list so they can work from the list and not have to keep the data in their head as they switch between item detail screens trying to plan how/where/what to pick.

**Comment by jcarlin** [comment]
**"2. Show total QOH for the warehouse and/or all warehouses"**... how about 1st field is QOH for the site/wh on the order and the 2nd column will total all additional sites if exist, otherwise be blank?

**Comment by jcarlin** [comment]
I suppose we can keep this in the design of the Transaction Lists but put the columns on the right side so that they don't clutter small displays. However, #2214 may satisfy this requirement.
