### ISSUE TITLE
Barcode scans should work for data entry

### ISSUE THREAD

**Issue by bendiy** [xtuple/xtuple#2216]
A user should be able to scan the following to input data on edit screens if they are in the right field:
1. Tracking numbers (UPS, FedEx, LTL)
2. Lot number for Relocate or Receiving when you need to specify the new lot number
3. Bin numbers for location tracking. Should be able to scan the Bin number instead of entering it by hand.

![receive-lot](https://cloud.githubusercontent.com/assets/571574/6217659/6397abc6-b5d3-11e4-9586-746af7dba272.png)

**Comment by bendiy** [comment]
This may be working correctly now, but we need to verify that the `*` prefix and carriage return are stripped out. If it's a UPC-A format and includes the vendor pre-fix, it should be stripped too.

**Comment by gilmoskowitz** [comment]
fixed by https://github.com/xtuple/private-extensions/pull/680
