### ISSUE TITLE
Add label report for Work Order Maintain Material Issue

### ISSUE THREAD

**Issue by bendiy** [xtuple/xtuple#2217]
Similar to the issue to shipping label report. They want to put labels on items when they transfer to production that say what work order the materials are for. 
![wo-item-label](https://cloud.githubusercontent.com/assets/571574/6217767/9fa30cd6-b5d4-11e4-8a11-5f5db272e194.png)

![wo-issue-item-print-label](https://cloud.githubusercontent.com/assets/571574/6218523/0aa604d2-b5dc-11e4-9373-5924f6e02f56.png)

There are some other details for what should be on the label, but need more discovery on that.
1. What info should be on the label? WO# Qty? Location? Lot?
2. How many labels should print? One for each line? One for each Qty?

**Comment by jcarlin** [comment]
This incident no longer needs to 'add' the label report for issue material. The report will live in OpenRPT and will be printable after https://github.com/xtuple/xtuple/issues/2187 is resolved.

**Comment by gilmoskowitz** [comment]
partially resolved by https://github.com/xtuple/private-extensions/pull/584

**Comment by jcarlin** [comment]
Resolved https://github.com/xtuple/private-extensions/pull/691.
