### ISSUE TITLE
WO Issue Material should redirect back to WO List of Activities List after Post Production

### ISSUE THREAD

**Issue by bendiy** [xtuple/xtuple#2218]
Similar issue with Issue to Shipping -> Ship Order. It brings you back to the Issue to Shipping item list for that order, but all items have been issued, so the list is empty and the user has to select `< Back` to get back to the list of orders.

![wo-post-redirect](https://cloud.githubusercontent.com/assets/571574/6218591/f6f398e0-b5dc-11e4-83b0-11b443673f4c.png)

**Comment by bendiy** [comment]
This is a confusing UX issue because after you've posted the activity, you end up back on this same list of items you started from, make it seem like what you just did did not happen.

**Comment by jcarlin** [comment]
Resolved in https://github.com/xtuple/private-extensions/pull/633
