### ISSUE TITLE
Add scanned variables concept to transaction lists

### ISSUE THREAD

**Issue by jcarlin** [xtuple/xtuple#2233]
The 3 variables are:
- location
- lot/serial*
- item #*

*These may be condensed into 1 variable if a company has concatenated item # and lot/serial into a single barcode. The code should be smart enough to recognize if the barcode contained both lot/serial and item # and handle it appropriately.
Upon scan of a single variable: 
- the UI will search the list for item's that contain the variable, if none found a popup will display telling the user that barcode x is not found. See issue #2215 
- the UI will reorder the list, placing the found item(s) at the top
- the scanned value will populate green on the matching line item(s) with the remaining required variable(s) colored red so that the user can clearly see remaining required scans
- upon scanning of all required variables on a single matching line item, all the scanned values will turn green on the line item and a qty of 1 will be transacted. In order to issue additional qty 1 with the scanner the user will need to repeat this sequence of required variable scans. See issue #2208 
- upon success of dispatch function the list item will update appropriately; reset the scanned variables, reorder sending the line item to the bottom of the list if full qty issued.

**Comment by bendiy** [comment]
We should have some way to designate the warehouse for the user so the list of items will resort with lines in the current warehouse at the top.
