### ISSUE TITLE
Transaction Lists should dynamically reorder

### ISSUE THREAD

**Issue by jcarlin** [xtuple/xtuple#2234]
Fully transacted line items:
- should place fully transacted line items at the bottom 
- have a div bar separating the fully transacted line items

Incomplete line items:
- an additional div bar/line item section? 
- some other visual indicator?

**Comment by bendiy** [comment]
![issue-to-shipping-list-notes](https://cloud.githubusercontent.com/assets/571574/6717736/4f49ee5a-cd74-11e4-97bf-331fddd9de5a.png)
