### ISSUE TITLE
SO Line Item Characteristics

### ISSUE THREAD

**Issue by zrichmond** [xtuple/xtuple#2240]
Installed version 4.8.1 with a copy of current production database, but I cannot view/edit item characteristics via web interface.  Items do have characteristics that are viewable/editable via desktop.  I have been able to view/edit item characteristics within a PO Line Item.  Just wondering if there is something I am missing?

**Comment by zrichmond** [comment]
Hoping this will make it into 4.9.  Also are you still using milestones for issues related to each release,  or is there a better place to look for Mobile roadmap information?

**Comment by jcarlin** [comment]
@zrichmond We have recently switched from github back to xTuple `Incidents` for our issue tracker (https://mobile.xtuple.com), but still pay attention to anything on github obviously.
Are you referring to simply maintaining item characteristics in the item master or to _all_ of the characteristic features in the UI? 
![screen shot 2015-05-29 at 1 30 07 pm](https://cloud.githubusercontent.com/assets/1823527/7891003/070c4158-0607-11e5-9b52-37ea0e0cac86.png)

**Comment by zrichmond** [comment]
I am referring to Sales Order Line entry in the Web UI.  There doesn't seem to be any way to specify characteristics like one can in the desktop.

![screen shot 2015-05-29 at 15 37 08](https://cloud.githubusercontent.com/assets/1100048/7892306/f7bc391c-0618-11e5-9a01-c8bddccab938.png)
 

Thanks for pointing me back to the issue tracker, GitHub is great, but I am more than happy to use either.

**Comment by bendiy** [comment]
@zrichmond You are correct. You can click on the folder icon to see more details for the line, but we're still missing characteristics.
![line-item-chars](https://cloud.githubusercontent.com/assets/571574/7892562/bb3d5b0c-0612-11e5-8904-542182c3ccf3.png)

**Comment by zrichmond** [comment]
Are there plans to implement this soon?  That's part of why I was wondering about the Milestones being up to date and curious about the current state of the roadmap particularly for completing some of the web UI.

**Comment by gilmoskowitz** [comment]
@zrichmond - it's on the list (obviously!) but no, we're not keeping the milestones up to date right now. we're in the midst of the 4.9.0 release cycle (beta was released recently and we're getting ready to build an rc) and haven't had a chance to look forward to 4.10 priorities yet.

**Comment by zrichmond** [comment]
For us having complete SO entry would be a huge step toward using the Enyo UI.  Thanks for the update and keep up the good work.

**Comment by zrichmond** [comment]
Any chance of getting this into 4.10?

**Comment by nedlilly** [comment]
Hey Zak - this is something that would require commercial sponsorship to bump up the priority list.  We'll be talking about the 4.10 priority list soon, in the next week or two.

**Comment by zrichmond** [comment]
Thanks for the note.  I'll get ahold of Jim then.
