### ISSUE TITLE
Want to change Vendor "Number"

### ISSUE THREAD

**Issue by comtineo01** [xtuple/xtuple#2247]
After discovering the only 'Look up' for Vendors within xTuple is based on 'Vendor Number', it makes far more sense for us to use the actual Vendor Names as their 'numbers' rather than the clerks needing to keep a 200+ name list on their desk to look up the numbers for efficient data entry.

If I re-import the Vendor Master with the new 'Vendor Numbers', will it update the other tables or do I need to hunt down every table that references that item and import to all of them also?

**Comment by davidbeauchamp** [comment]
If you clear the vendors list and re-import, the database will assign new internal id's to those new rows -- which is just a convoluted way to say that you would need to redo the imports for anything else that relies on those vendors, such as item sources and alternate addresses or open AP documents. 

Have you imported any other data that relies on vendors?

**Comment by comtineo01** [comment]
As to Imports - Just the Vendor Address one, but I still have the map etc for that, so shouldn't be a problem.

Unfortunately, I have manually GJ the 2014 Balance sheet and AP info tho. So there are some Vendors with 'current' vouchers and Credit Memo's.....I was naively hoping those would auto-update...hmmm
