### ISSUE TITLE
Bank Rec Import

### ISSUE THREAD

**Issue by comtineo01** [xtuple/xtuple#2282]
Trying to set up the Import for the Bank Rec and not getting much input on the xTuple forums, so I thought I'd give it a shot here.

I think I've found the table/view I should map....bankrecimport ?

Question about what a few of the fields are tho - 
bankrecimport_id = Bank Account Number? Or the closing date in integer form? or?

bankrecimport_reference = Check Number ?

bankrecimport_descrip = Payer/Payee name?  If so, do I need to manually edit out the "Debit Card Pament to" etc stuff on each line?

bankrecimport_curr_rate = I've no idea what this is...

**Comment by garyhgohoos** [comment]
There is a "standard" csv import map.  You will probably have to change depending on the format of your file.  Note that there are pre and post sql procedures.  I will attach map to forum post.
