### ISSUE TITLE
Issue installing 4.9 RC

### ISSUE THREAD

**Issue by discountscott** [xtuple/xtuple#2354]
Issue while install 4.9RC using webmin. what we ended up with when trying to install Quickstart DB was a 4.4 database...

n info xt.database Running...
n info cmd cd /usr/local/jack/.xtuple/dist/4.9.0-rc/xtuple && sudo -u jack node /usr/local/jack/.xtuple/dist/4.9.0-rc/xtuple/scripts/build_app.js -c /etc/xtuple/jack-490-rc-live/config.js -d quickstart_live -i -s /usr/local/jack/.xtuple/dist/4.9.0-rc/xtuple/foundation-database/quickstart_data.sql
npm WARN package.json backbone@0.9.10 No repository field.
npm WARN optional dep failed, continuing fsevents@0.3.6
bower d3                           extra-resolution Unnecessary resolution: d3#~3.4.4
error: Please add the line, plv8.start_proc = 'xt.js_init', to your postgresql.conf and restart the database server. error: Please add the line, plv8.start_proc = 'xt.js_init', to your postgresql.conf and restart the database server.
    at Connection.parseE (/usr/local/jack/.xtuple/dist/4.9.0-rc/xtuple/node_modules/pg/lib/connection.js:508:11)
    at Connection.parseMessage (/usr/local/jack/.xtuple/dist/4.9.0-rc/xtuple/node_modules/pg/lib/connection.js:368:17)
    at Socket. (/usr/local/jack/.xtuple/dist/4.9.0-rc/xtuple/node_modules/pg/lib/connection.js:84:20)
    at Socket.emit (events.js:95:17)
    at Socket. (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10) length=164, name=error, severity=ERROR, code=P0001, detail=undefined, hint=undefined, position=undefined, internalPosition=undefined, internalQuery=undefined, where=undefined, file=pl_exec.c, line=3035, routine=exec_stmt_raise
n ERR! cmd failed cd /usr/local/jack/.xtuple/dist/4.9.0-rc/xtuple && sudo -u jack node /usr/local/jack/.xtuple/dist/4.9.0-rc/xtuple/scripts/build_app.js -c /etc/xtuple/jack-490-rc-live/config.js -d quickstart_live -i -s /usr/local/jack/.xtuple/dist/4.9.0-rc/xtuple/foundation-database/quickstart_data.sql
n ERR! cmd status 1
n ERR! cmd stdout info: Dropping database quickstart_live
n ERR! cmd stdout info: Creating database quickstart_live
n ERR! cmd stdout info: Building schema for database quickstart_live
n ERR! cmd stdout info: Populating data for database quickstart_live from /usr/local/jack/.xtuple/dist/4.9.0-rc/xtuple/foundation-database/quickstart_data.sql
n ERR! cmd stdout  setval 
n ERR! cmd stdout --------
n ERR! cmd stdout     136
n ERR! cmd stdout (1 row)
n ERR! cmd stdout 
n ERR! cmd stdout  setval 
n ERR! cmd stdout --------
n ERR! cmd stdout       3
n ERR! cmd stdout (1 row)
n ERR! cmd stdout 
n ERR! cmd stdout  setval 
n ERR! cmd stdout --------
n ERR! cmd stdout       1
n ERR! cmd stdout (1 row)
n ERR! cmd stdout 
n ERR! cmd stdout  setval 
n ERR! cmd stdout --------
n ERR! cmd stdout      20
n ERR! cmd stdout (1 row)
n ERR! cmd stdout 
n ERR! cmd stdout  setval 
n ERR! cmd stdout --------

**Comment by bendiy** [comment]
@discountscott 
`error: Please add the line, plv8.start_proc = 'xt.js_init', to your postgresql.conf and restart the database server.`
Please see our wiki on this:
https://github.com/xtuple/xtuple/wiki/Installing-PLv8

We are now requiring the PLV8 extension be installed on the database and setup in the postgresql.conf.

**Comment by discountscott** [comment]
@bendiy 
Doesn't the xtuple-server install create the postgresql.conf??

If I add it now - it'll just get overwritten if I try to install distribution edition again using webmin. Correct?

**Comment by bendiy** [comment]
@discountscott Correct. You are on an "old" version of xtuple-server, so this change is not in it's code base. There is a patch for it here:
https://github.com/xtuple/xtuple-server-core/pull/515

That will ensure new "instances" created by xtuple-server have the setting in the new postgresql.conf files it creates.

**Comment by discountscott** [comment]
@bendiy Worked perfect when I applied that patch to our install. Thanks!

**Comment by bendiy** [comment]
Great!
