### ISSUE TITLE
'custom_variable_classes' disappeared in 9.2

### ISSUE THREAD

**Issue by paladinlogic** [xtuple/xtuple#2417]
If you try to follow the steps at https://github.com/xtuple/xtuple/wiki/Installing-PLv8 on PostgreSQL>=9.2 you will receive the following error:
> unrecognized configuration parameter "custom_variable_classes" in file "/etc/postgresql/9.3/main/postgresql.conf" line 597

For more information, refer to http://www.postgresql.org/docs/9.3/interactive/release-9-2.html#AEN117369 and http://www.postgresql.org/docs/9.2/static/runtime-config-custom.html

**Comment by gilmoskowitz** [comment]
Thank you for pointing this out. The wiki page has been updated.
