### ISSUE TITLE
Issue querying shipment resources - REST

### ISSUE THREAD

**Issue by discountscott** [xtuple/xtuple#2423]
When querying shipment records for a SO number in 4.9 I get an error.

Trying to access the following: 
`/dfsupply/api/v1alpha1/resources/shipment/?access_token=xxxx&query[order.number][EQUALS]=6017916`

I get the following error in 4.9. This was working fine in 4.8
```
{
  "error": {
    "code": 500,
    "message": "Error: operator does not exist: uuid = integer",
    "errors": [
      {
        "message": "Error: operator does not exist: uuid = integer"
      }
    ]
  }
}
```

**Comment by bendiy** [comment]
@discountscott Can you try applying this patch to your database?
https://github.com/xtuple/xtuple/pull/2424

To apply the patch, run this query:
https://raw.githubusercontent.com/bendiy/xtuple/query-inverse/lib/orm/source/xt/javascript/data.sql

It should fix the issue.

**Comment by discountscott** [comment]
Perfect. Thank you!
