### ISSUE TITLE
js_init

### ISSUE THREAD

**Issue by discountscott** [xtuple/xtuple#2432]
Maybe someone can shed some light on the following for me...

When we try to insert records directly in the Postgresql db that have a UUID generated by the mobile extension we sometimes get an error that XT is not defined.

If we start the statement with xt.js_init() it works - but after 4.9 that throws some errors periodically about  "function(msg, args) " and other times it works fine.

Is there a better way to be doing this?? I'm under the understanding that everything has been moving away from using js_init - but what should we be using instead?

One of the queries in question is the following:
insert into charass (charass_target_type,charass_target_id,charass_char_id,charass_value) values ('SO',(select cohead_id from cohead where cohead_number = 'xxxx'),(select char_id from char where char_name = 'Package Insurance'),'YES')

**Comment by bendiy** [comment]
@discountscott Have you done this to your `postgresql.conf`?
https://github.com/xtuple/xtuple/wiki/Installing-PLv8#on-all-platforms

Making this change, `xt.js_init()` will be ran before ANY plv8 function and removes the need for you to worry about calling it manually.

**Comment by discountscott** [comment]
OH - that would make sense @bendiy !

We did do that when we upgraded to 4.9... So now we don't need to call it anymore!

THANKS!
