### ISSUE TITLE
Installing 4.9.1 generated an error

### ISSUE THREAD

**Issue by discountscott** [xtuple/xtuple#2488]
Installing 4.9.1 generated an error for us. Some npm modules are failing to install. 4.9.0 is running just find on this server.

n info cmd cd /usr/local/xtuple/dist/4.9.1/xtuple && /usr/local/bin/npm install --unsafe-perm
npm WARN engine paynode@0.3.6: wanted: {"node":"~0.6.7"} (current: {"node":"0.10.32","npm":"1.4.28"})
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: incorrect header check
gyp ERR! stack     at Zlib._binding.onerror (zlib.js:295:17)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/xtuple/dist/4.9.1/xtuple/node_modules/bcrypt
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: incorrect header check
gyp ERR! stack     at Zlib._binding.onerror (zlib.js:295:17)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/xtuple/dist/4.9.1/xtuple/node_modules/pg
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: incorrect header check
gyp ERR! stack     at Zlib._binding.onerror (zlib.js:295:17)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/xtuple/dist/4.9.1/xtuple/node_modules/zombie/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing contextify@0.1.14
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.10.32","npm":"1.4.28"})
npm ERR! bcrypt@0.8.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.3 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--unsafe-perm"
npm ERR! cwd /usr/local/xtuple/dist/4.9.1/xtuple
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
n WARN cmd retrying
npm WARN package.json backbone@0.9.10 No repository field.
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: incorrect header check
gyp ERR! stack     at Zlib._binding.onerror (zlib.js:295:17)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/xtuple/dist/4.9.1/xtuple/node_modules/bcrypt
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! bcrypt@0.8.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.3 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--unsafe-perm"
npm ERR! cwd /usr/local/xtuple/dist/4.9.1/xtuple
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
n WARN cmd retrying
npm WARN package.json backbone@0.9.10 No repository field.
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: incorrect header check
gyp ERR! stack     at Zlib._binding.onerror (zlib.js:295:17)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/xtuple/dist/4.9.1/xtuple/node_modules/bcrypt
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! bcrypt@0.8.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.3 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--unsafe-perm"
npm ERR! cwd /usr/local/xtuple/dist/4.9.1/xtuple
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
n ERR! cmd failed cd /usr/local/xtuple/dist/4.9.1/xtuple && /usr/local/bin/npm install --unsafe-perm
n ERR! cmd status 1
n ERR! cmd stdout 
n ERR! cmd stdout > xtuple@4.9.1 preinstall /usr/local/xtuple/dist/4.9.1/xtuple
n ERR! cmd stdout > cd node-datasource/lib/query ; npm install
n ERR! cmd stdout 
n ERR! cmd stdout 
n ERR! cmd stdout > bcrypt@0.8.3 install /usr/local/xtuple/dist/4.9.1/xtuple/node_modules/bcrypt
n ERR! cmd stdout > node-gyp rebuild
n ERR! cmd stdout 
n ERR! cmd stdout 
n ERR! cmd stderr npm WARN package.json backbone@0.9.10 No repository field.
n ERR! cmd stderr gyp WARN install got an error, rolling back install
n ERR! cmd stderr gyp ERR! configure error 
n ERR! cmd stderr gyp ERR! stack Error: incorrect header check
n ERR! cmd stderr gyp ERR! stack     at Zlib._binding.onerror (zlib.js:295:17)
n ERR! cmd stderr gyp ERR! System Linux 3.13.0-24-generic
n ERR! cmd stderr gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
n ERR! cmd stderr gyp ERR! cwd /usr/local/xtuple/dist/4.9.1/xtuple/node_modules/bcrypt
n ERR! cmd stderr gyp ERR! node -v v0.10.32
n ERR! cmd stderr gyp ERR! node-gyp -v v1.0.1
n ERR! cmd stderr gyp ERR! not ok 
n ERR! cmd stderr 
n ERR! cmd stderr npm ERR! bcrypt@0.8.3 install: `node-gyp rebuild`
n ERR! cmd stderr npm ERR! Exit status 1
n ERR! cmd stderr npm ERR! 
n ERR! cmd stderr npm ERR! Failed at the bcrypt@0.8.3 install script.
n ERR! cmd stderr npm ERR! This is most likely a problem with the bcrypt package,
n ERR! cmd stderr npm ERR! not with npm itself.
n ERR! cmd stderr npm ERR! Tell the author that this fails on your system:
n ERR! cmd stderr npm ERR!     node-gyp rebuild
n ERR! cmd stderr npm ERR! You can get their info via:
n ERR! cmd stderr npm ERR!     npm owner ls bcrypt
n ERR! cmd stderr npm ERR! There is likely additional logging output above.
n ERR! cmd stderr npm ERR! System Linux 3.13.0-24-generic
n ERR! cmd stderr npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--unsafe-perm"
n ERR! cmd stderr npm ERR! cwd /usr/local/xtuple/dist/4.9.1/xtuple
n ERR! cmd stderr npm ERR! node -v v0.10.32
n ERR! cmd stderr npm ERR! npm -v 1.4.28
n ERR! cmd stderr npm ERR! code ELIFECYCLE
n ERR! cmd stderr npm ERR! not ok code 0
n ERR! cmd stderr 
n ERR! xtuple Command failed: cd /usr/local/xtuple/dist/4.9.1/xtuple && /usr/local/bin/npm install --unsafe-perm
n ERR! xtuple npm WARN package.json backbone@0.9.10 No repository field.
n ERR! xtuple gyp WARN install got an error, rolling back install
n ERR! xtuple gyp ERR! configure error 
n ERR! xtuple gyp ERR! stack Error: incorrect header check
n ERR! xtuple gyp ERR! stack     at Zlib._binding.onerror (zlib.js:295:17)
n ERR! xtuple gyp ERR! System Linux 3.13.0-24-generic
n ERR! xtuple gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
n ERR! xtuple gyp ERR! cwd /usr/local/xtuple/dist/4.9.1/xtuple/node_modules/bcrypt
n ERR! xtuple gyp ERR! node -v v0.10.32
n ERR! xtuple gyp ERR! node-gyp -v v1.0.1
n ERR! xtuple gyp ERR! not ok 
n ERR! xtuple 
n ERR! xtuple npm ERR! bcrypt@0.8.3 install: `node-gyp rebuild`
n ERR! xtuple npm ERR! Exit status 1
n ERR! xtuple npm ERR! 
n ERR! xtuple npm ERR! Failed at the bcrypt@0.8.3 install script.
n ERR! xtuple npm ERR! This is most likely a problem with the bcrypt package,
n ERR! xtuple npm ERR! not with npm itself.
n ERR! xtuple npm ERR! Tell the author that this fails on your system:
n ERR! xtuple npm ERR!     node-gyp rebuild
n ERR! xtuple npm ERR! You can get their info via:
n ERR! xtuple npm ERR!     npm owner ls bcrypt
n ERR! xtuple npm ERR! There is likely additional logging output above.
n ERR! xtuple npm ERR! System Linux 3.13.0-24-generic
n ERR! xtuple npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--unsafe-perm"
n ERR! xtuple npm ERR! cwd /usr/local/xtuple/dist/4.9.1/xtuple
n ERR! xtuple npm ERR! node -v v0.10.32
n ERR! xtuple npm ERR! npm -v 1.4.28
n ERR! xtuple npm ERR! code ELIFECYCLE
n ERR! xtuple npm ERR! not ok code 0
n ERR! xtuple 
n info xtuple Please see xtuple-server.log for more info

**Comment by bendiy** [comment]
@discountscott 
```
npm ERR! bcrypt@0.8.3 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.3 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
```

We've been having random issues with npm installing packages. Sometimes it works fine, sometimes it doesn't.

What happens when you do:
```
cd /usr/local/xtuple/dist/4.9.1/xtuple
npm install
```

**Comment by discountscott** [comment]
@bendiy I get a similar error about bcrypt.

administrator@df-xtuple:/usr/local/xtuple/dist/4.9.1/xtuple$ sudo npm install
[sudo] password for administrator:
npm WARN cannot run in wd xtuple@4.9.1 cd node-datasource/lib/query ; npm instal                                                                                                                                                             l (wd=/usr/local/xtuple/dist/4.9.1/xtuple)
npm WARN package.json backbone@0.9.10 No repository field.
-
> bcrypt@0.8.3 install /usr/local/xtuple/dist/4.9.1/xtuple/node_modules/bcrypt
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: incorrect header check
gyp ERR! stack     at Zlib._binding.onerror (zlib.js:295:17)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/b                                                                                                                                                             in/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/xtuple/dist/4.9.1/xtuple/node_modules/bcrypt
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! bcrypt@0.8.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.3 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /usr/local/xtuple/dist/4.9.1/xtuple
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by bendiy** [comment]
@discountscott Can you try installing node version 0.10.40?
Either:
```
n 0.10.40
```
or 
```
nvm install 0.10.40
```

**Comment by discountscott** [comment]
@bendiy 
Same error...

```
npm WARN cannot run in wd xtuple@4.9.1 cd node-datasource/lib/query ; npm install (wd=/usr/local/xtuple/dist/4.9.1/xtuple)
npm WARN package.json backbone@0.9.10 No repository field.
\
> bcrypt@0.8.3 install /usr/local/xtuple/dist/4.9.1/xtuple/node_modules/bcrypt
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: incorrect header check
gyp ERR! stack     at Zlib._binding.onerror (zlib.js:296:17)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/xtuple/dist/4.9.1/xtuple/node_modules/bcrypt
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! bcrypt@0.8.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.3 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /usr/local/xtuple/dist/4.9.1/xtuple
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by bendiy** [comment]
@discountscott 
The other thing I'm seeing that look out of date is `npm`. Try this:
```
sudo npm install npm -g
```
and
```
npm -v
```
Should return `2.13.4`.

**Comment by bendiy** [comment]
@discountscott 
Another thing you can try is to see if you can get just `bcrypt` to install at all:
```
cd ~
mkdir bcrypt-temp
cd bcrypt-temp
npm install bcrypt@0.8.3
```

**Comment by discountscott** [comment]
@bendiy 

I updated npm. As a side note - updating didn't move to version (2.13.4) we are now running (2.14.1)

Still getting the same error when running "xtuple-server install-live". It looks to me like it downgrades the versions when it runs... Is that true?

Because I get the same output where it shows the version as the old one...
```
npm WARN engine paynode@0.3.6: wanted: {"node":"~0.6.7"} (current: {"node":"0.10.32","npm":"1.4.28"})
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: incorrect header check
gyp ERR! stack     at Zlib._binding.onerror (zlib.js:295:17)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/xtuple/dist/4.9.1/xtuple/node_modules/bcrypt
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
```

**Comment by bendiy** [comment]
@discountscott 
Can you post a https://gist.github.com/ of the whole log? I suspect a key piece of infomation is missing a few lines above this from your first post:
```
n info cmd cd /usr/local/xtuple/dist/4.9.1/xtuple && /usr/local/bin/npm install --unsafe-perm
npm WARN engine paynode@0.3.6: wanted: {"node":"~0.6.7"} (current: {"node":"0.10.32","npm":"1.4.28"})
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: incorrect header check
gyp ERR! stack at Zlib._binding.onerror (zlib.js:295:17)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
```

I'm researching some related issues with this error and some of them are unable to access this link from behind their corporate firewall:
http://nodejs.org/dist/v0.10.32/node-v0.10.32.tar.gz

**Comment by bendiy** [comment]
A good check would be to see if you can install it to a temp directory like I posted above:
```
cd ~
mkdir bcrypt-temp
cd bcrypt-temp
npm install bcrypt@0.8.3
```

**Comment by discountscott** [comment]
@bendiy 

https://gist.github.com/discountscott/40a88471f43a6005b077

**Comment by discountscott** [comment]
@bendiy 
upon checking the firewall - you're absolutely right. Requests to that URL are being blocked.

I've white-listed and am trying again.

**Comment by discountscott** [comment]
@bendiy 

Works great now! Appreciate the help.

**Comment by bendiy** [comment]
Your welcome.
